#!/usr/bin/env python3

from babel_base import *
import re

if   re.match(r"https?://.*", args.TO):
    import babel_http
elif re.match(r"(\+\d{1,3})?\d{10}|\d{3}-\d{3}-\d{4}", args.TO):
    import babel_sms
else:
    fail("Couldn't parse recipient address.")